### Decide how much the player should be damaged!
JumpDMG: 1
### (1 Damage = 0.5 Hearts)
JumpMessageToggle: true
# ! RESTART REQUIRED!
JumpMessage: "You jumped!"
### The message that displays when you jump